# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='post title')),
                ('content', models.TextField(verbose_name='post content')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='post create date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='post author')),
            ],
            options={
                'verbose_name': 'post item',
                'verbose_name_plural': 'posts items',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_authors_set', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_subscriber_set', to=settings.AUTH_USER_MODEL, verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'subscription item',
                'verbose_name_plural': 'subscriptions items',
            },
        ),
        migrations.CreateModel(
            name='ViewMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Post', verbose_name='post')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'view mark item',
                'verbose_name_plural': 'view marks items',
            },
        ),
        migrations.AlterUniqueTogether(
            name='viewmark',
            unique_together=set([('post', 'subscriber')]),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('author', 'subscriber')]),
        ),
    ]
