# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20161220_0748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewmark',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='viewmark',
            name='post',
        ),
        migrations.RemoveField(
            model_name='viewmark',
            name='subscriber',
        ),
        migrations.DeleteModel(
            name='ViewMark',
        ),
    ]
